
// IMPORTING MONGOOSE
const mongoose=require("mongoose")

// IMPORTING THE RELEVANT MODEL
const Artist=require("../models/artistModel")

// DEFINING AND EXPORTING A SPECIFIC CONTROLLER METHOD
// GET ALL ARTISTS(ENTRIES) FROM THE ARTISTS COLLECTION
// USING ASYNC-AWAIT AND TRY-CATCH
exports.getArtists=